### ISSUE TITLE
Incorrect regex in webpack.config.dev.js

### ISSUE THREAD

**Issue by JeremyRH** [tsaiDavid/simple-redux-boilerplate#11]
https://github.com/tsaiDavid/simple-redux-boilerplate/blob/master/webpack.config.dev.js#L40

Shouldn't `/\.js?/` be `/\.js$/`?

**Comment by Rumpel78** [comment]
I think it should `/\.js$/` as you suggested, or `/\.jsx?$/` if jsx files are also supported.
