### ISSUE TITLE
SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by wooters** [tsaiDavid/simple-redux-boilerplate#3]
I'm getting the following error when I run `npm run dev`:

```
$ npm run dev

> generator-simple-redux@1.0.0 dev /home/wooters/projects/simple-redux-boilerplate
> NODE_ENV=development npm start

> generator-simple-redux@1.0.0 start /home/wooters/projects/simple-redux-boilerplate
> node devServer.js

/home/wooters/projects/simple-redux-boilerplate/devServer.js:16
app.get('*', (req, res) => {
                         ^
SyntaxError: Unexpected token >
       at Module._compile (module.js:439:25)
       at Object.Module._extensions..js (module.js:474:10)
       at Module.load (module.js:356:32)
       at Function.Module._load (module.js:312:12)
       at Function.Module.runMain (module.js:497:10)
       at startup (node.js:119:16)
       at node.js:929:3
npm ERR! weird error 8
npm ERR! not ok code 0
npm ERR! weird error 1
npm ERR! not ok code 0
```

I followed the directions in the README.md, namely, I did:
1. Forked your repo.
2. Cloned to my dev box.
3. `$ cd simple-redux-boilerplate`
4. `$ npm install`
5. `$ npm run dev`

That last step is what produced the error above.

**Comment by tsaiDavid** [comment]
@wooters - Hey there! Looks like you might be running on an older version of Node - which version are you using?

**Comment by wooters** [comment]
Hi David. when I run `$ node -v`, I get `v0.10.36`. 

I should mention that I'm a total noob at node/react, so your boilerplate is a **huge** help. Thanks for putting this together!

**Comment by tsaiDavid** [comment]
Hey @wooters - don't sweat it - so your node version is too low, the fat arrow function you see is part of the ES6 aka ES2015 specification, and it wasn't until the later versions that it was supported by running node with the `--harmony` flag! 

When playing with a lot of this newer React stuff, it can sometimes be best to have a later version of Node (if not different ones). I'd use a version manager like this:

https://www.npmjs.com/package/n

Go ahead and give that a try!

**Comment by tsaiDavid** [comment]
@wooters - If you use `n`, you can just have it install the latest version, so anytime you need to swap versions, you can just hit n and select one.

**Comment by wooters** [comment]
Wow! Awesome! Worked like a charm! Thanks very much for your help.
